# Generated by Django 6.0.4 on 2026-04-13 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "resume_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_saved_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="surveys.survey",
                    ),
                ),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="surveys.surveyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("value_encrypted", models.BinaryField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.surveyfield",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="responses.surveysubmission",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["survey", "status"], name="responses_s_survey__507e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["respondent", "status"], name="responses_s_respond_c1c7d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["resume_token"], name="responses_s_resume__1fb744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["survey", "submitted_at"], name="responses_s_survey__fc5829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["field", "value_text"], name="responses_a_field_i_62c14b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["field", "value_number"], name="responses_a_field_i_e9c947_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "field")},
        ),
    ]
