# Generated by Django 6.0.4 on 2026-04-13 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=1000)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("file_upload", "File Upload"),
                            ("rating", "Rating"),
                            ("matrix", "Matrix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                ("is_sensitive", models.BooleanField(default=False)),
                ("placeholder", models.CharField(blank=True, max_length=500)),
                ("help_text", models.TextField(blank=True)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("default_value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.surveyfield",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FieldDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            (
                                "options_filter",
                                "Filter target options based on source answer",
                            ),
                            ("visibility", "Show/hide target based on source answer"),
                            (
                                "required_if",
                                "Target becomes required based on source answer",
                            ),
                            (
                                "value_constraint",
                                "Constrain target value based on source answer",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_dependencies",
                        to="surveys.survey",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="surveys.surveyfield",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depends_on",
                        to="surveys.surveyfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveySection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="surveyfield",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="surveys.surveysection",
            ),
        ),
        migrations.CreateModel(
            name="SurveyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="VisibilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("section", "Section"), ("field", "Field")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "logical_operator",
                    models.CharField(
                        choices=[
                            ("AND", "All conditions must be true"),
                            ("OR", "Any condition must be true"),
                        ],
                        default="AND",
                        max_length=5,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_rules",
                        to="surveys.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisibilityCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not Equals"),
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("gte", ">="),
                            ("lte", "<="),
                            ("in", "In List"),
                            ("not_in", "Not In List"),
                            ("contains", "Contains"),
                            ("not_contains", "Not Contains"),
                            ("is_empty", "Is Empty"),
                            ("is_not_empty", "Is Not Empty"),
                            ("between", "Between"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_value", models.JSONField()),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_conditions",
                        to="surveys.surveyfield",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="surveys.visibilityrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["organization", "status"], name="surveys_sur_organiz_614e5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["status", "published_at"], name="surveys_sur_status_b5d842_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldoption",
            unique_together={("field", "value")},
        ),
        migrations.AddIndex(
            model_name="fielddependency",
            index=models.Index(
                fields=["survey"], name="surveys_fie_survey__329881_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddependency",
            index=models.Index(
                fields=["source_field"], name="surveys_fie_source__88c0dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddependency",
            index=models.Index(
                fields=["target_field"], name="surveys_fie_target__39fc22_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveysection",
            unique_together={("survey", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="surveyfield",
            unique_together={("section", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="surveyversion",
            unique_together={("survey", "version_number")},
        ),
        migrations.AddIndex(
            model_name="visibilityrule",
            index=models.Index(
                fields=["survey"], name="surveys_vis_survey__f3906e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visibilityrule",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="surveys_vis_target__18f424_idx",
            ),
        ),
    ]
